version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8001:8001"
    environment:
      DATABASE_URL: mysql://root:rootpassword@mysql:3306/mydatabase
    depends_on:
      - mysql
    networks:
      - microservice-network
    command: >
      sh -c "./wait-for-it.sh mysql 3306 --timeout=60 -- alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8001 --reload"

  attendance_control:
    build:
      context: ./attendance_control
      dockerfile: Dockerfile
    container_name: attendance-service
    ports:
      - "8002:8002"
    environment:
      DATABASE_URL: mysql://root:rootpassword@mysql:3306/mydatabase
    depends_on:
      - mysql
    networks:
      - microservice-network
    command: >
      sh -c "./wait-for-it.sh mysql 3306 --timeout=60 -- alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8002 --reload"


  academic_management:
    build:
      context: ./academic_management
      dockerfile: Dockerfile
    container_name: academic-service
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql://root:rootpassword@mysql:3306/mydatabase
    depends_on:
      - mysql
    networks:
      - microservice-network
    command: >
      sh -c "./wait-for-it.sh mysql 3306 --timeout=60 -- alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"


volumes:
  mysql-data:

networks:
  microservice-network:
    driver: bridge

