"""initial migration

Revision ID: 9952775b3e82
Revises: 
Create Date: 2024-10-06 08:21:02.302397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9952775b3e82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    op.drop_table('attendance')
    op.drop_table('classes')
    op.drop_table('users')
    op.drop_table('students_classes')
    op.drop_table('subjects')
    op.drop_index('user_email', table_name='professors')
    op.drop_table('professors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professors',
    sa.Column('id', mysql.VARCHAR(length=12), nullable=False),
    sa.Column('user_email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], name='professors_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('user_email', 'professors', ['user_email'], unique=True)
    op.create_table('subjects',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('students_classes',
    sa.Column('id_clase', mysql.VARCHAR(length=21), nullable=False),
    sa.Column('id_estudiante', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id_clase'], ['classes.id'], name='students_classes_ibfk_1'),
    sa.ForeignKeyConstraint(['id_estudiante'], ['students.id'], name='students_classes_ibfk_2'),
    sa.PrimaryKeyConstraint('id_estudiante', 'id_clase'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('email'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('classes',
    sa.Column('id', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('professor', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('subjet', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['professor'], ['professors.id'], name='classes_ibfk_1'),
    sa.ForeignKeyConstraint(['subjet'], ['subjects.id'], name='classes_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('attendance',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('class_id', mysql.VARCHAR(length=12), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=10), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name='attendance_ibfk_2'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='attendance_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('students',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=True),
    sa.Column('grade', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_email'], ['users.email'], name='students_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
