FROM python:3.9

WORKDIR /app

RUN apt-get update && apt-get install -y netcat-openbsd

COPY wait-for-it.sh .

RUN chmod +x wait-for-it.sh

COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .


EXPOSE 8001


CMD ["./wait-for-it.sh", "mysql", "3306", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]